CosmiQ/solaris

solaris/data/config_skeleton.yml
solaris/nets/_keras_losses.py
solaris/nets/_losses.py
solaris/nets/_torch_losses.py
solaris/nets/callbacks.py
solaris/nets/datagen.py
solaris/nets/losses.py
solaris/nets/metrics.py
solaris/nets/model_io.py
solaris/nets/train.py
solaris/vector/polygon.py

Fixes #30 
Please delete options that …

Adding pytorch and keras loss function wrappers, Lovasz Hinge, Focal Loss, composites

---

solaris/data/config_skeleton.yml
solaris/nets/callbacks.py
solaris/nets/optimizers.py
solaris/nets/torch_callbacks.py
solaris/nets/train.py

Adding wrappers for Keras callbacks and some minimal Torch callback functionality. The majority of torch callbacks are just written out/defined during training, so all I did for torch here was implement an `EarlyStopping` class and the learning rate scheduler wrapper for the optimizer.

adding callback functions

---

environment.yml
requirements.txt
solaris/data/config_skeleton.yml
solaris/nets/callbacks.py
solaris/nets/optimizers.py
solaris/nets/torch_callbacks.py
solaris/nets/train.py
solaris/utils/tile.py

Iss60 utilfunctions

---

solaris/data/config_skeleton.yml
solaris/utils/io.py
tests/test_utils/test_io.py

Added the ability to rescale images when loading in, with arguments in config_skeleton.yml

adding custom rescaling to image loading

---

docker/Dockerfile

Adding a dockerfile for building a solaris environment.

Iss90 dockerfile

---

environment.yml
requirements.txt
setup.py
solaris/nets/datagen.py
solaris/nets/infer.py
solaris/nets/model_io.py
solaris/nets/transform.py
solaris/nets/zoo.py
tests/test_nets/test_datagen.py
tests/test_raster/test_image.py

Debugging inference and adding XD_XD's SpaceNet 4 model architecture.

Iss105 inf debug

---

solaris/raster/image.py
solaris/utils/raster.py

Iss112 stitching

---

solaris/eval/baseeval.py
tests/test_eval/baseeval_test.py

Previously, storing the best IoU for each ground truth building during evaluation slowed down code execution.  Issue #119 suggested using a flag to turn this feature on and off as needed, but a better solution was …

Faster storing of ground truth buildings' IoUs

---

solaris/vector/mask.py
tests/test_vector/test_mask.py

Improves default behavior for the `do_transform` argument in mask creation: by default, now checks to see whether or not a CRS should be done based on the attributes of the input dataframe and the reference image or …

improving default behavior for do_transform

---

solaris/vector/mask.py

min mask val

---

solaris/eval/__init__.py
solaris/eval/pixel_metrics.py

Iss142 pix metrics

---

solaris/eval/baseeval.py

Adds functionality to eval to return the TP, FP, and FN gdfs that can be converted to a geojson for visualization, or used for retraining.
Fixes # 138
Please describe …

added function to eval

---

solaris/utils/geo.py
solaris/vector/mask.py

Just removing all calls to `sol.geo._check_wkt_load()` to replace with the slightly more flexible `sol.base._check_geom()`.

replacing _check_wkt_load calls

---

solaris/eval/base.py
solaris/tile/raster_tile.py

There are security issues with having empty lists as arguments; replacing them with `None`.
Fixes #8 
Please describe tests that you added to the pytest codebase (if …

ISS8: replacing empty lists with None

---

docker/cpu/Dockerfile
docker/gpu/Dockerfile
environment-gpu.yml

creating GPU and CPU-specific Dockerfiles

---

solaris/nets/datagen.py
solaris/nets/transform.py
solaris/utils/io.py
tests/test_nets/test_datagen.py
tests/test_raster/test_image.py

ISS173: removing automated dtype normalization; adding channel drop augmenter

---

docs/conf.py
solaris/__init__.py

bumping version

---

setup.py
solaris/vector/mask.py

Fixes #209 
Please delete options that …

ISS209: adding output to mask_to_poly_geojson

---

solaris/nets/configs/config_skeleton.yml
solaris/nets/configs/selimsef_densenet121unet_spacenet4.yml
solaris/nets/configs/selimsef_densenet161unet_spacenet4.yml
solaris/nets/configs/selimsef_resnet34unet_spacenet4.yml
solaris/nets/configs/xdxd_spacenet4.yml
solaris/nets/datagen.py
solaris/nets/infer.py
tests/test_nets/test_datagen.py

Provides flexibility in dtypes as well as debugging provision of newly trained models when using a custom model dict.
Fixes #246
Future model training/inference with torch _must_ use the `config['data_specs']['dtype']` parameter.

Iss246 dtype

---

CHANGELOG.md

Adding CHANGELOG.md to the top directory for recording changes.

ISS7: Adding changelog

---

requirements.txt

Closes #263 - just fixed the affine version pin in `requirements.txt`.

fixing affine version

---

solaris/eval/base.py
tests/test_eval/evaluator_test.py

This has hung around with no tests for long enough (and indeed I found a bug when I implemented the test). It appears to be working now.

ISS147: adding pytest for eval_iou_return_GDFs()

---

docker/cpu/Dockerfile

When trying to build the cpu docker container I came across a bug in the dockerfile. This fixes the bug.
- [x ] Bug fix (non-breaking change which fixes an issue)
Now I'm able to build the cpu docker container …

Fix apt-get install step of cpu dockerfile

---

solaris/data/coco.py
tests/test_data/test_coco.py

Adds model confidence scoring (as required for coco scoring), also a bugfix for segmentation polygons included.
Please describe tests that you added to the …

added scoring + bug fix

---

.travis.yml

Adding Python 3.8 build to Travis CI.

ISS274: adding python 3.8 build

---

solaris/nets/_keras_losses.py
solaris/nets/train.py
solaris/nets/zoo/selim_sef_sn4.py

ISS256: Remove extra weight downloads for selim_sef SN4 models

---

solaris/nets/transform.py

Add SwapChannels to __all__

---

docs/tutorials/notebooks/api_tiling_tutorial.ipynb

fixing links for tiling tutorial

---

solaris/nets/_torch_losses.py

Constructor for TorchDiceLoss class now acceptions optional argument to specify whether to apply a sigmoid function to the input prior to further calculations.  This option defaults to "False," replicating the class's previous behavior.
Fixes # 281

Optionally apply sigmoid function to TorchDiceLoss input

---

CHANGELOG.md

Updated changelog to reflect feature additions from issues 281 and 282

Added features for issues 281 and 282 to changelog

---

CHANGELOG.md
solaris/utils/__init__.py
solaris/utils/data.py
tests/test_utils/test_data.py

Wrote a function to automatically create dataset CSVs (`sol.utils.data.make_dataset_csv()`) with enough flexibility to accommodate most simple use cases.
Fixes #241  …

ISS241: automated dataset csv creation

---

CHANGELOG.md
solaris/vector/mask.py

Sets the nodata metadata to zero in output mask files generated by footprint_mask().  Also fixes a minor variable type bug in the same function.
Fixes #295
Please describe …

Set mask nodata value to 0

---

environment-gpu.yml
environment.yml

Fixes # 299
Added the `requests` package to both `environment.yml` files. `requests` is used by `nets/model_io.py`.

Add requests to both environment.yml files.

---

environment-gpu.yml
environment.yml

`WindowsError`s (see https://github.com/Toblerity/rtree/issues/130 get thrown with specific combinations of rtree and python that are problems. Pinning to 0.9.1 seems to fix it.
Fixes # 303
Please delete options that …

ISS303: pinning rtree to 0.9.1

---

CHANGELOG.md
solaris/tile/raster_tile.py
solaris/utils/geo.py
solaris/vector/mask.py

I found the tile bounds issue by trying to use `split_geom` via the raster tiler to tile a single Landsat scene that partially intersected with the state of Nebraska (my `aoi_boundary`). This resulted in many empty tiles because tile bounds outside the landsat image were included.
The instance_mask issue is shown here:
Where the tile partially falls outside the raster image labels shouldn't be created because no data values like -9999.0 will be associated with those labels. This also handles issues that could arise if there are no data values in the corners of rasters (like there are for some Landsat collections).
I self tested on my own datasets and ran this against existing tests. Whereas before the `aoi_boundary` fix the following tile would be empty and before the `isntance_mask` fix …

aoi_boundary should intersect reference image in split_geom and instance_mask should only rasterize vectors where there are valid pixels

---

solaris/utils/core.py

The initial PR for this subject (#319) didn't quite resolve all of the problems. This PR finishes it.
Fixes #317

Finish fixing CRS management (ISS317 part 2)

---

CHANGELOG.md
docs/conf.py
solaris/__init__.py

See the CHANGELOG.md for changes that were included.

Release v0.2.1

---

environment-gpu.yml
environment.yml

Reverting version of GDAL since latest version causes an issue with Fiona.
Fixes #343
_If your …

Pinning GDAL version to resolve compatibility issue with Fiona

---

CHANGELOG.md
docs/conf.py
solaris/__init__.py

Preparing to merge into master for v0.2.2. Updating version pins, minor changes to `CHANGELOG.md`
_If your PR does not fulfill all of the requirements in the checklist …

Release version 0.2.2

---

CHANGELOG.md
docs/api/utils.rst

Adds an API reference entry for utils.data
Not yet tested (will be tested with readthedocs and modified if necessary)

API reference entry for utils.data

---

docs/api/index.rst
docs/api/preproc.rst

Adds API Reference for preproc subpackage.
Not yet tested; will be examined on readthedocs

API reference for preprocessing library

---

docs/api/preproc.rst
docs/conf.py

Attempt to resolve documentation building issue by adding pyproj to autodoc_mock_imports
Not yet tested; will check documentation build after pull.

Docs preprocessing

---

docs/conf.py

Update intersphinx_mapping for numpy
Will be tested on readthedocs build after merge.

Update intersphinx_mapping for numpy

---

CHANGELOG.md
solaris/nets/torch_callbacks.py
solaris/nets/train.py

- Model checkpoint frequency parameter in YAML model specification files is active now
- Fixes Bug #353 
_If your PR does not fulfill all of the requirements in the …

Model Checkpoint Frequency (Bug 353)

---

CHANGELOG.md
solaris/bin/make_graphs.py
solaris/bin/make_masks.py
solaris/data/coco.py
solaris/eval/base.py
solaris/nets/model_io.py
solaris/tile/raster_tile.py
solaris/tile/vector_tile.py
solaris/vector/mask.py

- Fixes tqdm progress bar issue
- Fixes issue #335 
_If your PR does not fulfill all of the …

tqdm Progress Bar Issue (Bug #335)

---

solaris/nets/infer.py
solaris/raster/image.py

Infer fix
Fixes # 367
To do
_If your PR does not fulfill all of the requirements in the checklist above, that's OK!_ Just prepend [WIP] to the PR title until they are all …

inference fix

---

.readthedocs-environment.yml

Read the docs build error fix attempt
Not yet tested; will test readthedocs build after pull
_If your PR does not fulfill all of the requirements in the checklist above, …

readthedocs build error fix

---

environment-gpu.yml
environment.yml

Added cudatoolkit=9.2 which is a requirement for working with pytorch and cuda 9.2
_If your PR …

Conda yaml fix

---

solaris/nets/configs/config_skeleton.yml
solaris/nets/datagen.py
solaris/nets/model_io.py
solaris/nets/train.py
solaris/nets/zoo/__init__.py
solaris/nets/zoo/multiclass_segmentation.py

Adding more models to the model zoo and the ability to create multiclass outputs.
Fixes #  45 …

Multiclass nets

---

solaris/eval/vector.py
tests/test_eval/vector_test.py

Bug fix for when a proposal class doesn't overlap with the ground truth and speed improvements …

Expanded metrics v3

---

solaris/eval/vector.py
tests/test_eval/vector_test.py

Bug fix
_If your PR does not fulfill all of the requirements in the checklist …

Expanded metrics v4

---

solaris/preproc/__init__.py
solaris/preproc/image.py
solaris/preproc/optical.py
solaris/preproc/pipesegment.py
solaris/tile/raster_tile.py

This pull request fixes a longstanding tiler bug where pixels beyond the edge of the source imagery have indeterminate value.  This request also adds some features to the preprocessing library:
*Option to set the size of ShowImage output and add accompanying caption
*An "optical" module, currently with classes for converting color spaces
*Reverting the multiprocessing command

Tiler fix and preprocessing features

---

CHANGELOG.md
docs/conf.py
solaris/__init__.py

Updating version to 0.3.0
- 20200701, dphogan: Added multimodal preprocessing subpackage (#360)
- 20200716, dphogan: Added three-part tutorial for preprocessing subpackage
- 20200630, dphogan: Remove edge case numeric values from loss function tests (#358)
- 20200706, dphogan: Added API reference entry for utils.data
- 20200706, roshanr11: fixed `checkpoint_frequency` parameter in YAML files to work as intended
- 20200706, roshanr11: tqdm progress bar fixed, follow-up on previous issue (#335)
_If your PR does not fulfill all of the requirements in the checklist above, that's OK!_ Just prepend [WIP] to the PR title until they are all satisfied. If you need help, …

Updating version to 0.3.0

---

solaris/eval/vector.py
tests/test_eval/vector_test.py

adding mAP metric

---

solaris/eval/__init__.py
solaris/eval/challenges.py
solaris/eval/scot.py

Adds the SpaceNet Change and Object Tracking (SCOT) metric to the eval subpackage, including the file scot.py with the metric itself, and a multi_temporal_buildings function in challenges.py to load and score …

SpaceNet Change and Object Detection (SCOT) metric

---

CHANGELOG.md
solaris/eval/challenges.py
solaris/eval/scot.py

Option to output dictionary of statistics from all AOIs with SCOT metric (turned off by default)
No tests added to codebase.
_If your PR does not fulfill all of the …

Output multi-AOI statistics with SCOT metric

---

solaris/eval/vector.py

Fixed hardcoded threshold of 0.5 IOU in a few eval functions
_If your PR does …

Fixed hardcoded threshold of 0.5 IOU
